name: Continuous Deployment

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gridsome Installation
        run: sudo npm install -g @gridsome/cli

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: gridsome build

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v2
        env:
          EMAIL: ivansantosgonz@gmail.com
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_DIR: dist
          CNAME: ivansantosgonzalez.dev
